language: python
cache: pip
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.7-dev"

install:
  - pip install 'requests>=2.7'
  - pip install coveralls
  - pip install vcrpy

script:
  - nosetests -v --cover-package=habanero

after_success:
  - coveralls --verbose
